[appearance]
theme = "textual-dark"
# theme = "full_documented_theme"
# theme = "tokyo-night"

[autocomplete]
enabled = true

# if you put commands section with out any commands then there will be no commands
# if you want to use custom commands and the original commands then you need to
# re define them
# [commands]
# through the first ren these are the default commands
# send = "send" # simply sends whatever comes after it
# r = "r" # toggles return line carry feed \r
# n = "n" # toggles newline \n
# rl = "rl" # reloads the config
# reload = "reload" # reloads the config
# rn = "rn" # toggles both \r and \n
# e = "e" # toggles echo
# echo = "echo" # toggles echo
# togglec = "togglec" # toggles device connection for selected device
# c = "c" # toggles device connection for selected device
# con = "con" # connects to selected device disconnects and reconnects if already connected
# connect = "connect" # connects to selected device disconnects and reconnects if already connected
# dis = "dis" # disconnects from selected device does nothing if already disconnected
# disconnect = "disconnect" # disconnects from selected device does nothing if already disconnected
# s = "s" # opens device selection screen
# select = "select" # opens device selection screen
# clear = "clear" # clears output
# l = "l" # clears output
# th = "th" # lets you set the throttle rate using th <ms>, Ex: th 100
# throttle = "th" # same as th
# flush = "fl" # flushes all queued commands that where throtteled
# flush = "flush" # flushes all queued commands that where throtteled
# ren = "ren" # toggles \r \n and echo

# you can do a list to execute multiple commands in a row
# ren = ["rn", "echo"] # ren is a built in command but this is how you can make a command call multiple
# you can do <command> <arg> aswell
# t5 = ["fl", "th 50"] clears the buffer and sets the throttle to 50 ms

# you can provide a descriptions for any command builtin or custom
# you get autocomplete suggestions in the popup
# [command_descriptions]
# "ren" = "toggles both newlines and echo"

# [keybindings]
# through ctrl+c these are the default keybindings:
# "ctrl+s" = "s"
# "ctrl+l" = "l"
# "ctrl+r" = "r"
# "ctrl+n" = "n"
# "ctrl+e" = "e"
# "ctrl+g" = "rl"
# "ctrl+p" = "p"
# "ctrl+h" = "c"
# "ctrl+f" = "fl"
# "ctrl+c" = "q"

# you can bind a key to a command that takes arguments like this
# "ctrl+t" = "th 50"
# "ctrl+t" = "send CMD"

[[devices]]
name = "charachorder"
description_pattern = "(?i)charachorder"
throttle_ms = 100
auto_n = true
auto_r = true
baud_rate = 115200
