[ui]
theme = "textual-dark"
# theme = "full_documented_theme"
# theme = "tokyo-night"
header_visible = true
footer_max_height = 2  # set to 0 to hide the footer, this is the max height if less rows can be used to display the bindings they will
shorten_bindings = false  # substatues ctrl+ with ^

[history]
size = 100  # navigte the history by pressin the autoocmplete navigation keys (up, down, ctrl+j,ctrl+k) while the suggestions are not empty

[autocomplete]
enabled = true

# if you put commands section with out any commands then there will be no commands
# if you want to use custom commands and the original commands then you need to
# re define them
# [commands]
# through the first ren these are the default commands
# send = "send" # simply sends whatever comes after it
# r = "r" # toggles return line carry feed \r
# n = "n" # toggles newline \n
# reload_config = "reload_config" # reloads the config
# reload = "reload" # reloads the config
# rl = "rl" # reloads the config
# rn = "rn" # toggles both \r and \n
# e = "e" # toggles echo
# echo = "echo" # toggles echo
# toggle_connection = "toggle_connection" # toggles device connection for selected device
# c = "c" # toggles device connection for selected device
# con = "con" # connects to selected device disconnects and reconnects if already connected
# connect = "connect" # connects to selected device disconnects and reconnects if already connected
# dis = "dis" # disconnects from selected device does nothing if already disconnected
# disconnect = "disconnect" # disconnects from selected device does nothing if already disconnected
# select_device = "select_device" # opens device selection screen
# select = "select" # opens device selection screen
# s = "s" # opens device selection screen
# clear = "clear" # clears output
# l = "l" # clears output
# th = "th" # lets you set the throttle rate using th <ms>, Ex: th 100
# throttle = "th" # same as th
# flush = "flush_buf" # flushes all queued things to be sent that where throtteled
# flush = "flush" # flushes all queued things to be sent that where throtteled
# flush = "fl" # flushes all queued things to be sent that where throtteled
# ren = "ren" # toggles \r \n and echo
# device_info = "device_info" # prints the info for the current device
# cmds = "cmds" # prints out all  commands available to the user to the output section
# keys = "keys" # prints out all commands available to the user to the output section

# you can do a list to execute multiple commands in a row
# ren = ["rn", "echo"] # ren is a built in command but this is how you can make a command call multiple
# you can do <command> <arg> aswell
# t5 = ["fl", "th 50"] # clears the buffer and sets the throttle to 50 ms

# you can provide a descriptions for any command builtin or custom
# you get autocomplete suggestions in the popup
# [command_descriptions]
# "ren" = "toggles both newlines and echo"

# [keybindings]
# through ctrl+c these are the default keybindings:
# "ctrl+s" = "select_device"
# "ctrl+l" = "clear"
# "ctrl+r" = "r"
# "ctrl+n" = "n"
# "ctrl+e" = "echo"
# "ctrl+g" = "reload_config"
# "ctrl+p" = "command_pallett"
# "ctrl+h" = "toggle_connection"
# "ctrl+f" = "flush_buf"
# "ctrl+c" = "quit"

# you can bind a key to a command that takes arguments like this
# "ctrl+t" = "th 50"
# "ctrl+t" = "send CMD"
# "ctrl+t" = ["fl", "th 50"]  # clears the buffer and sets the throttle to 50 ms

[[devices]]
name = "charachorder"
description_pattern = "(?i)charachorder"
throttle_ms = 100
auto_n = true
auto_r = true
baud_rate = 115200
